enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

npmRegistries:
  "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/":
    npmAuthToken: NpmToken.f7bcd249-9f95-3c73-a5b2-86b3c5b7276c

npmScopes:
  codefi:
    npmRegistryServer: "https://nexus.eu-west-3.codefi.network/repository/npm-hosted/"
